force-app/main/default/objects/Account/fields/CAZ_Correo_institucional__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Correo_institucional__c</fullName>
    <label>CAZ_Correo_institucional</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZ_Direccion_plantilla_B__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Direccion_plantilla_B__c</fullName>
    <formula>BillingStreet &amp; &apos;, &apos; &amp; 
CAZB_No_interior__c &amp; &apos;, &apos; &amp; 
CAZB_No_exterior__c &amp; &apos;, &apos; &amp; 
CAZB_Colonia__c &amp; &apos;, &apos; &amp; 
BillingPostalCode &amp; &apos;, &apos; &amp; 
CAZB_Municipio__c &amp; &apos;, &apos; &amp; 
BillingCity &amp; &apos;, &apos; &amp; 
BillingState  &amp; &apos;, &apos; &amp; 
BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CAZ_Direccion_plantilla_B</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZ_Direccion_plantilla_S__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Direccion_plantilla_S__c</fullName>
    <formula>ShippingStreet &amp; &apos;, &apos; &amp; 
CAZS_No_interior__c &amp; &apos;, &apos; &amp; 
CAZS_No_exterior__c &amp; &apos;, &apos; &amp; 
CAZS_Colonia__c &amp; &apos;, &apos; &amp; 
ShippingPostalCode &amp; &apos;, &apos; &amp; 
CAZS_Municipio__c &amp; &apos;, &apos; &amp; 
ShippingCity &amp; &apos;, &apos; &amp; 
ShippingState  &amp; &apos;, &apos; &amp; 
ShippingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CAZ_Direccion_plantilla_S</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZ_IdExterno__c.field-meta.xml
<CustomField>
    <fullName>CAZ_IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>CAZ_IdExterno</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CAZB_Colonia__c.field-meta.xml
<CustomField>
    <fullName>CAZB_Colonia__c</fullName>
    <label>CAZB_Colonia</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZB_Municipio__c.field-meta.xml
<CustomField>
    <fullName>CAZB_Municipio__c</fullName>
    <label>CAZB_Municipio</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZB_No_exterior__c.field-meta.xml
<CustomField>
    <fullName>CAZB_No_exterior__c</fullName>
    <label>CAZB_No. exterior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZB_No_interior__c.field-meta.xml
<CustomField>
    <fullName>CAZB_No_interior__c</fullName>
    <label>CAZB_No. interior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZS_Colonia__c.field-meta.xml
<CustomField>
    <fullName>CAZS_Colonia__c</fullName>
    <label>CAZS_Colonia</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZS_Municipio__c.field-meta.xml
<CustomField>
    <fullName>CAZS_Municipio__c</fullName>
    <label>CAZS_Municipio</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZS_No_exterior__c.field-meta.xml
<CustomField>
    <fullName>CAZS_No_exterior__c</fullName>
    <label>CAZS_No. exterior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CAZS_No_interior__c.field-meta.xml
<CustomField>
    <fullName>CAZS_No_interior__c</fullName>
    <label>CAZS_No. interior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/Solicitud_de_actualizacion_de_datos__c.object-meta.xml
<CustomObject>
    <label>Solicitud de actualización de datos</label>
    <nameField>
        <displayFormat>SAD-{000000000}</displayFormat>
        <label>SAD</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes de actualización de datos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZ_Correo_institucional__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Correo_institucional__c</fullName>
    <label>CAZ_Correo_institucional</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZ_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CAZ_Cuenta</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No se encontró información que coincida con los filtros</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CAZ Información propia</value>
        </filterItems>
        <infoMessage>Registros de clientes propios</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Actualización de datos</relationshipLabel>
    <relationshipName>Solicitudes_de_actualizaci_n_de_datos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZ_Direccion_plantilla_B__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Direccion_plantilla_B__c</fullName>
    <label>CAZ_Direccion_plantilla_B</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZ_Direccion_plantilla_S__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Direccion_plantilla_S__c</fullName>
    <label>CAZ_Direccion_plantilla_S</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZ_Email__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Email__c</fullName>
    <label>CAZ_Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZ_IdExterno__c.field-meta.xml
<CustomField>
    <fullName>CAZ_IdExterno__c</fullName>
    <label>CAZ_IdExterno</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZB_Calle__c.field-meta.xml
<CustomField>
    <fullName>CAZB_Calle__c</fullName>
    <label>CAZB_Calle</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZB_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>CAZB_Ciudad__c</fullName>
    <label>CAZB_Ciudad</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZB_CodigoPostal__c.field-meta.xml
<CustomField>
    <fullName>CAZB_CodigoPostal__c</fullName>
    <label>CAZB_CodigoPostal</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZB_Colonia__c.field-meta.xml
<CustomField>
    <fullName>CAZB_Colonia__c</fullName>
    <label>CAZB_Colonia</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZB_Estado__c.field-meta.xml
<CustomField>
    <fullName>CAZB_Estado__c</fullName>
    <label>CAZB_Estado</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZB_Municipio__c.field-meta.xml
<CustomField>
    <fullName>CAZB_Municipio__c</fullName>
    <label>CAZB_Municipio</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZB_No_exterior__c.field-meta.xml
<CustomField>
    <fullName>CAZB_No_exterior__c</fullName>
    <label>CAZB_No. exterior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZB_No_interior__c.field-meta.xml
<CustomField>
    <fullName>CAZB_No_interior__c</fullName>
    <label>CAZB_No. interior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZB_Pais__c.field-meta.xml
<CustomField>
    <fullName>CAZB_Pais__c</fullName>
    <label>CAZB_Pais</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPB_Calle__c.field-meta.xml
<CustomField>
    <fullName>CAZPB_Calle__c</fullName>
    <label>CAZPB_Calle</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPB_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>CAZPB_Ciudad__c</fullName>
    <label>CAZPB_Ciudad</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPB_CodigoPostal__c.field-meta.xml
<CustomField>
    <fullName>CAZPB_CodigoPostal__c</fullName>
    <label>CAZPB_CodigoPostal</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPB_Colonia__c.field-meta.xml
<CustomField>
    <fullName>CAZPB_Colonia__c</fullName>
    <label>CAZPB_Colonia</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPB_Estado__c.field-meta.xml
<CustomField>
    <fullName>CAZPB_Estado__c</fullName>
    <label>CAZPB_Estado</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPB_Municipio__c.field-meta.xml
<CustomField>
    <fullName>CAZPB_Municipio__c</fullName>
    <label>CAZPB_Municipio</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPB_No_exterior__c.field-meta.xml
<CustomField>
    <fullName>CAZPB_No_exterior__c</fullName>
    <label>CAZPB_No_exterior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPB_No_interior__c.field-meta.xml
<CustomField>
    <fullName>CAZPB_No_interior__c</fullName>
    <label>CAZPB_No_interior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPB_Pais__c.field-meta.xml
<CustomField>
    <fullName>CAZPB_Pais__c</fullName>
    <label>CAZPB_Pais</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPS_Calle__c.field-meta.xml
<CustomField>
    <fullName>CAZPS_Calle__c</fullName>
    <label>CAZPS_Calle</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPS_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>CAZPS_Ciudad__c</fullName>
    <label>CAZPS_Ciudad</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPS_CodigoPostal__c.field-meta.xml
<CustomField>
    <fullName>CAZPS_CodigoPostal__c</fullName>
    <label>CAZPS_CodigoPostal</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPS_Colonia__c.field-meta.xml
<CustomField>
    <fullName>CAZPS_Colonia__c</fullName>
    <label>CAZPS_Colonia</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPS_Estado__c.field-meta.xml
<CustomField>
    <fullName>CAZPS_Estado__c</fullName>
    <label>CAZPS_Estado</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPS_Municipio__c.field-meta.xml
<CustomField>
    <fullName>CAZPS_Municipio__c</fullName>
    <label>CAZPS_Municipio</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPS_No_exterior__c.field-meta.xml
<CustomField>
    <fullName>CAZPS_No_exterior__c</fullName>
    <label>CAZPS_No_exterior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPS_No_interior__c.field-meta.xml
<CustomField>
    <fullName>CAZPS_No_interior__c</fullName>
    <label>CAZPS_No_interior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZPS_Pais__c.field-meta.xml
<CustomField>
    <fullName>CAZPS_Pais__c</fullName>
    <label>CAZPS_Pais</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZS_Calle__c.field-meta.xml
<CustomField>
    <fullName>CAZS_Calle__c</fullName>
    <label>CAZS_Calle</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZS_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>CAZS_Ciudad__c</fullName>
    <label>CAZS_Ciudad</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZS_CodigoPostal__c.field-meta.xml
<CustomField>
    <fullName>CAZS_CodigoPostal__c</fullName>
    <label>CAZS_CodigoPostal</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZS_Colonia__c.field-meta.xml
<CustomField>
    <fullName>CAZS_Colonia__c</fullName>
    <label>CAZS_Colonia</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZS_Estado__c.field-meta.xml
<CustomField>
    <fullName>CAZS_Estado__c</fullName>
    <label>CAZS_Estado</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZS_Municipio__c.field-meta.xml
<CustomField>
    <fullName>CAZS_Municipio__c</fullName>
    <label>CAZS_Municipio</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZS_No_exterior__c.field-meta.xml
<CustomField>
    <fullName>CAZS_No_exterior__c</fullName>
    <label>CAZS_No. exterior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZS_No_interior__c.field-meta.xml
<CustomField>
    <fullName>CAZS_No_interior__c</fullName>
    <label>CAZS_No. interior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZS_Pais__c.field-meta.xml
<CustomField>
    <fullName>CAZS_Pais__c</fullName>
    <label>CAZS_Pais</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SActualizacionDato_cuenta.cls
public class SActualizacionDato_cuenta {
    public static void actualizaCampos(list<Solicitud_de_actualizacion_de_datos__c> triggerNew) {
        // Definicion de variables
        list<String> idCuentas = new list<String>();
        list<Account> registroCuentas = new list<Account>();
        map<String, Account> mapaCuentas = new map<String, Account>();

        // Se extraen los Ids para consultar los registros
        for(Solicitud_de_actualizacion_de_datos__c forData : triggerNew) {
            idCuentas.add(forData.CAZ_Cuenta__c);
        }
        system.debug('SActualizacionDato ::: idCuentas ::: ' + idCuentas);

        // Se consulta la información de la Cuenta para mostrarlos como solo lectura
        if(!idCuentas.isEmpty()) {
            // select Id, CAZB_Colonia__c, CAZB_Municipio__c, CAZB_No_exterior__c, CAZB_No_interior__c, CAZS_Colonia__c, CAZS_Municipio__c, CAZS_No_exterior__c, CAZS_No_interior__c, BillingCity, BillingCountry, BillingPostalCode, BillingState, BillingStreet, ShippingCity, ShippingCountry, ShippingPostalCode, ShippingState, ShippingStreet, CAZ_IdExterno__c, CAZ_Correo_institucional__c, CAZ_Direccion_plantilla_B__c, CAZ_Direccion_plantilla_S__c from Account where Id IN : idCuentas
            registroCuentas = Database.query(system.label.CAZ_Cuenta_soloLectura);
            system.debug('registroCuentas ::: size ::: ' + registroCuentas.size());

            // Se agrupa la informacion
            if(!registroCuentas.isEmpty()) {
                for(Account forData : registroCuentas) {
                    mapaCuentas.put(forData.Id, forData);
                }
                system.debug('mapaCuentas ::: size ::: ' + mapaCuentas.size());
            }
        }

        // Se consulta la informacion de la Cuenta y se asigna a la solicitud de informacion
        if(!registroCuentas.isEmpty()) {
            for(Solicitud_de_actualizacion_de_datos__c forData : triggerNew) {
                // Se extrae la informacion especifica del objeto de Cuenta
                Account cuentaForData = mapaCuentas.get(forData.CAZ_Cuenta__c);

                // Campos
                forData.CAZB_Ciudad__c = cuentaForData.BillingCity;
                forData.CAZB_Pais__c = cuentaForData.BillingCountry;
                forData.CAZB_CodigoPostal__c = cuentaForData.BillingPostalCode;
                forData.CAZB_Estado__c = cuentaForData.BillingState;
                forData.CAZB_Calle__c = cuentaForData.BillingStreet;
                // - - - - -
                forData.CAZS_Ciudad__c = cuentaForData.ShippingCity;
                forData.CAZS_Pais__c = cuentaForData.ShippingCountry;
                forData.CAZS_CodigoPostal__c = cuentaForData.ShippingPostalCode;
                forData.CAZS_Estado__c = cuentaForData.ShippingState;
                forData.CAZS_Calle__c = cuentaForData.ShippingStreet;
                // - - - - -
                forData.CAZB_Colonia__c = cuentaForData.CAZB_Colonia__c;
                forData.CAZB_Municipio__c = cuentaForData.CAZB_Municipio__c;
                forData.CAZB_No_exterior__c = cuentaForData.CAZB_No_exterior__c;
                forData.CAZB_No_interior__c = cuentaForData.CAZB_No_interior__c;
                // - - - - -
                forData.CAZS_Colonia__c = cuentaForData.CAZS_Colonia__c;
                forData.CAZS_Municipio__c = cuentaForData.CAZS_Municipio__c;
                forData.CAZS_No_exterior__c = cuentaForData.CAZS_No_exterior__c;
                forData.CAZS_No_interior__c = cuentaForData.CAZS_No_interior__c;
                // - - - - -
                forData.CAZ_IdExterno__c = cuentaForData.CAZ_IdExterno__c;
                forData.CAZ_Email__c = cuentaForData.CAZ_Correo_institucional__c;
                // - - - - -
                forData.CAZ_Correo_institucional__c = cuentaForData.CAZ_Correo_institucional__c;
                forData.CAZ_Direccion_plantilla_B__c = cuentaForData.CAZ_Direccion_plantilla_B__c;
                forData.CAZ_Direccion_plantilla_s__c = cuentaForData.CAZ_Direccion_plantilla_S__c;
            }
        }
    }

    public static void autoActualizacion(list<Solicitud_de_actualizacion_de_datos__c> triggerNew) {
        // Definicion de variables
        list<Account> registroCuentas = null;
        map<String, Solicitud_de_actualizacion_de_datos__c> sad_cuenta = new map<String, Solicitud_de_actualizacion_de_datos__c>();
        map<String, Account> query_cuenta = new map<String, Account>();

        // Se extrae la informacion
        for(Solicitud_de_actualizacion_de_datos__c forData : triggerNew) {
            sad_cuenta.put(forData.CAZ_IdExterno__c, forData);
        }

        // Se consulta y organiza la informacion de la Cuenta
        registroCuentas = [select Id, CAZB_Colonia__c, CAZB_Municipio__c, CAZB_No_exterior__c, CAZB_No_interior__c, CAZS_Colonia__c, CAZS_Municipio__c, CAZS_No_exterior__c, CAZS_No_interior__c, BillingCity, BillingCountry, BillingPostalCode, BillingState, BillingStreet, ShippingCity, ShippingCountry, ShippingPostalCode, ShippingState, ShippingStreet, CAZ_IdExterno__c, CAZ_Correo_institucional__c, CAZ_Direccion_plantilla_B__c, CAZ_Direccion_plantilla_S__c from Account where CAZ_IdExterno__c IN : sad_cuenta.keySet()];
        for(Account forData : registroCuentas) {
            Solicitud_de_actualizacion_de_datos__c sadTemp = sad_cuenta.get(forData.CAZ_IdExterno__c);
            forData.CAZB_Colonia__c = sadTemp.CAZPB_Colonia__c;
            forData.CAZB_Municipio__c = sadTemp.CAZPB_Municipio__c;
            forData.CAZB_No_exterior__c = sadTemp.CAZPB_No_exterior__c;
            forData.CAZB_No_interior__c = sadTemp.CAZPB_No_interior__c;
            forData.CAZS_Colonia__c = sadTemp.CAZPS_Colonia__c;
            forData.CAZS_Municipio__c = sadTemp.CAZPS_Municipio__c;
            forData.CAZS_No_exterior__c = sadTemp.CAZPS_No_exterior__c;
            forData.CAZS_No_interior__c = sadTemp.CAZPS_No_interior__c;
            forData.BillingCity = sadTemp.CAZPB_Ciudad__c;
            forData.BillingCountry = sadTemp.CAZPB_Pais__c;
            forData.BillingPostalCode = sadTemp.CAZPB_CodigoPostal__c;
            forData.BillingState = sadTemp.CAZPB_Estado__c;
            forData.BillingStreet = sadTemp.CAZPB_Calle__c;
            forData.ShippingCity = sadTemp.CAZPS_Ciudad__c;
            forData.ShippingCountry = sadTemp.CAZPS_Pais__c;
            forData.ShippingPostalCode = sadTemp.CAZPS_CodigoPostal__c;
            forData.ShippingState = sadTemp.CAZPS_Estado__c;
            forData.ShippingStreet = sadTemp.CAZPS_Calle__c;
            forData.CAZ_Correo_institucional__c = sadTemp.CAZP_Email__c;
        }

        // Se guarda la informacion y se finaliza el flujo
        // Se actualiza el registro. false: indica que se insertaran tantos registros sean posibles
        Database.SaveResult[] dbsr = Database.update(registroCuentas, false);
        for(Database.SaveResult forData : dbsr) {
            if(forData.isSuccess()) {
                system.debug('Registro actualizado correctamente');
                system.debug('Registro a enviar: ' + forData.Id);
                //Id jobID = System.enqueueJob(new SActualizacionDato_solicitud(true, forData.Id), 1);
                Id jobID = System.enqueueJob(new SActualizacionDato_solicitud(true, forData.Id));
            }
            else {
                for(Database.Error forDataError : forData.getErrors()) {
                    system.debug('Error ::: ' + 'Detalle ::: ' + forDataError.getStatusCode() + ' ::: ' + forDataError.getMessage() + ' ::: Afectando los campos: ' + forDataError.getFields());
                }
                //Id jobID = System.enqueueJob(new SActualizacionDato_solicitud(false, forData.Id), 1);
                Id jobID = System.enqueueJob(new SActualizacionDato_solicitud(false, forData.Id));
            }
        }
    }
}