force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/Solicitud_de_actualizacion_de_datos__c.object-meta.xml
<CustomObject>
    <label>Solicitud de actualización de datos</label>
    <nameField>
        <displayFormat>SAD-{000000000}</displayFormat>
        <label>SAD</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes de actualización de datos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZ_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CAZ_Cuenta</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No se encontró información que coincida con los filtros</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CAZ Información propia</value>
        </filterItems>
        <infoMessage>Registros de clientes propios</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Actualización de datos</relationshipLabel>
    <relationshipName>Solicitudes_de_actualizaci_n_de_datos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZ_Estado__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Estado__c</fullName>
    <label>CAZ_Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recibido</fullName>
                <default>true</default>
                <label>Recibido</label>
            </value>
            <value>
                <fullName>En aprobación</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solicitud_de_actualizacion_de_datos__c/fields/CAZ_VieneDeWS__c.field-meta.xml
<CustomField>
    <fullName>CAZ_VieneDeWS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CAZ_VieneDeWS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SActualizacionDato_solicitud.cls
public class SActualizacionDato_solicitud implements Queueable {
    public Boolean exitoError {get; set;}
    public String idRegistro {get; set;}

    public SActualizacionDato_solicitud(Boolean er, String idr) {
        exitoError = er;
        idRegistro = idr;
    }

    public void execute(QueueableContext context) {
        system.debug('Exito / error: ' + exitoError);
        system.debug('Registro: ' + idRegistro);

        String idTR = Schema.SObjectType.Solicitud_de_actualizacion_de_datos__c.getRecordTypeInfosByDeveloperName().get(system.label.SActualizacionDato_developerName).getRecordTypeId();
        system.debug('idTR: ' + idTR);

        // Se consulta el registro de Solicitudes de actualización de datos para actualizar su estado
        // select Id, CAZ_Estado__c from Solicitud_de_actualizacion_de_datos__c where CAZ_Cuenta__c =: idRegistro and CAZ_VieneDeWS__c = true and RecordTypeId =: idTR and CAZ_Estado__c = 'Recibido'
        list<Solicitud_de_actualizacion_de_datos__c> actualizaEstado = Database.query(system.label.CAZ_SAD_aceptada);
        system.debug('actualizaEstado: ' + actualizaEstado.size());

        for(Solicitud_de_actualizacion_de_datos__c forData : actualizaEstado) {
            forData.CAZ_Estado__c = exitoError ? 'Aprobado' : 'Rechazado';
            system.debug('forData.CAZ_Estado__c: ' + forData.CAZ_Estado__c);
        }
        Database.update(actualizaEstado,false);
    }
}