force-app/main/default/objects/CAZ_Checklist_Monitoreo__c/CAZ_Checklist_Monitoreo__c.object-meta.xml
<CustomObject>
    <label>Checklist de Monitoreo</label>
    <nameField>
        <displayFormat>CHK-{00000}</displayFormat>
        <label>Checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists de Monitoreo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAZ_Checklist_Monitoreo__c/fields/CAZ_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>CAZ_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Checklists de Monitoreo</relationshipLabel>
    <relationshipName>ChecklistMonitoreoCuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CAZ_CkDistCtrl.cls
public with sharing class CAZ_CkDistCtrl {
    public PageReference go() {
        String accountId = getAccountId();
        String target = '/lightning/o/CAZ_Checklist_Monitoreo__c/new?recordTypeId=012WD000001XukPYAS';

        if (String.isNotBlank(accountId)) {
            target += '&defaultFieldValues=' +
                EncodingUtil.urlEncode('CAZ_Cuenta__c=' + accountId, 'UTF-8');
        }

        PageReference nextPage = new PageReference(target);
        nextPage.setRedirect(true);
        return nextPage;
    }

    private String getAccountId() {
        Map<String, String> params = ApexPages.currentPage().getParameters();
        List<String> keys = new List<String>{ 'id', 'recordId', 'recordIds', 'ids', 'sfid', 'whatId', 'parentId' };

        for (String key : keys) {
            String value = params.get(key);
            if (String.isNotBlank(value)) {
                return value.split(',')[0];
            }
        }

        return null;
    }
}